require 'murlsh/server/base_server'

require 'murlsh/server/atom_server'
require 'murlsh/server/json_server'
require 'murlsh/server/m3u_server'
require 'murlsh/server/podcast_server'
require 'murlsh/server/pop_server'
require 'murlsh/server/random_server'
require 'murlsh/server/rss_server'
require 'murlsh/server/url_server'
